<?php

/**
 * Enum representing the available virtual account channels.
 */
const VIRTUAL_ACCOUNT_CHANNELS = [
    'VIRTUAL_ACCOUNT_BCA',
    'VIRTUAL_ACCOUNT_BANK_MANDIRI',
    'VIRTUAL_ACCOUNT_BANK_SYARIAH_MANDIRI',
    'VIRTUAL_ACCOUNT_BRI',
    'VIRTUAL_ACCOUNT_BNI',
    'VIRTUAL_ACCOUNT_DOKU',
    'VIRTUAL_ACCOUNT_PERMATA',
    'VIRTUAL_ACCOUNT_BANK_CIMB',
    'VIRTUAL_ACCOUNT_DANAMON',
];
