<?php

/**
 * Enum representing the available virtual account channels.
 */
abstract class VIRTUAL_ACCOUNT_CHANNELS
{
    const VIRTUAL_ACCOUNT_BCA = 'VIRTUAL_ACCOUNT_BCA';
    const VIRTUAL_ACCOUNT_BANK_MANDIRI = 'VIRTUAL_ACCOUNT_BANK_MANDIRI';
    const VIRTUAL_ACCOUNT_BANK_SYARIAH_MANDIRI = 'VIRTUAL_ACCOUNT_BANK_SYARIAH_MANDIRI';
    const VIRTUAL_ACCOUNT_BRI = 'VIRTUAL_ACCOUNT_BRI';
    const VIRTUAL_ACCOUNT_BNI = 'VIRTUAL_ACCOUNT_BNI';
    const VIRTUAL_ACCOUNT_DOKU = 'VIRTUAL_ACCOUNT_DOKU';
    const VIRTUAL_ACCOUNT_PERMATA = 'VIRTUAL_ACCOUNT_PERMATA';
    const VIRTUAL_ACCOUNT_CIMB = 'VIRTUAL_ACCOUNT_CIMB';
    const VIRTUAL_ACCOUNT_DANAMON = 'VIRTUAL_ACCOUNT_DANAMON';
}